local asciimojis = {
	{ ["text"] = "acid", ["subText"] = "⊂(◉‿◉)つ" },
	{ ["text"] = "afraid", ["subText"] = "(ㆆ _ ㆆ)" },
	{ ["text"] = "alpha", ["subText"] = "α" },
	{ ["text"] = "angel", ["subText"] = "☜(⌒▽⌒)☞" },
	{ ["text"] = "angry", ["subText"] = "•`_´•" },
	{ ["text"] = "arrowhead", ["subText"] = "⤜(ⱺ ʖ̯ⱺ)⤏" },
	{ ["text"] = "apple", ["subText"] = "" },
	{ ["text"] = "ass,butt", ["subText"] = "(‿|‿)" },
	{ ["text"] = "awkward", ["subText"] = "•͡˘㇁•͡˘" },
	{ ["text"] = "bat", ["subText"] = "/|\\ ^._.^ /|\\" },
	{ ["text"] = "bear,koala", ["subText"] = "ʕ·͡ᴥ·ʔ﻿" },
	{ ["text"] = "bearflip", ["subText"] = "ʕノ•ᴥ•ʔノ ︵ ┻━┻" },
	{ ["text"] = "bearhug", ["subText"] = "ʕっ•ᴥ•ʔっ" },
	{ ["text"] = "because,since", ["subText"] = "∵" },
	{ ["text"] = "beta", ["subText"] = "β" },
	{ ["text"] = "bigheart", ["subText"] = "❤" },
	{ ["text"] = "blackeye", ["subText"] = "0__#" },
	{ ["text"] = "blubby", ["subText"] = "(      0    _   0    )" },
	{ ["text"] = "blush", ["subText"] = "(˵ ͡° ͜ʖ ͡°˵)" },
	{ ["text"] = "bond,007", ["subText"] = "┌( ͝° ͜ʖ͡°)=ε/̵͇̿̿/’̿’̿ ̿" },
	{ ["text"] = "boobs", ["subText"] = "( . Y . )" },
	{ ["text"] = "bored", ["subText"] = "(-_-)" },
	{ ["text"] = "bribe", ["subText"] = "( •͡˘ _•͡˘)ノð" },
	{ ["text"] = "bubbles", ["subText"] = "( ˘ ³˘)ノ°ﾟº❍｡" },
	{ ["text"] = "butterfly", ["subText"] = "ƸӜƷ" },
	{ ["text"] = "cat", ["subText"] = "(= ФェФ=)" },
	{ ["text"] = "catlenny", ["subText"] = "( ͡° ᴥ ͡°)﻿" },
	{ ["text"] = "checkmark,check", ["subText"] = "✔" },
	{ ["text"] = "cheer", ["subText"] = "※\\(^o^)/※" },
	{ ["text"] = "chubby", ["subText"] = "╭(ʘ̆~◞౪◟~ʘ̆)╮" },
	{ ["text"] = "claro", ["subText"] = "(͡ ° ͜ʖ ͡ °)" },
	{
		["text"] = "clique,gang,squad",
		["subText"] = "ヽ༼ ຈل͜ຈ༼ ▀̿̿Ĺ̯̿̿▀̿ ̿༽Ɵ͆ل͜Ɵ͆ ༽ﾉ",
	},
	{ ["text"] = "cloud", ["subText"] = "☁" },
	{ ["text"] = "club", ["subText"] = "♣" },
	{ ["text"] = "coffee,cuppa", ["subText"] = "c[_]" },
	{ ["text"] = "command,cmd", ["subText"] = "⌘" },
	{ ["text"] = "cool,csi", ["subText"] = "(•_•) ( •_•)>⌐■-■ (⌐■_■)" },
	{ ["text"] = "copyright,copy,c", ["subText"] = "©" },
	{ ["text"] = "creep", ["subText"] = "ԅ(≖‿≖ԅ)" },
	{ ["text"] = "creepcute", ["subText"] = "ƪ(ړײ)‎ƪ​​" },
	{ ["text"] = "crim3s", ["subText"] = "( ✜︵✜ )" },
	{ ["text"] = "cross", ["subText"] = "†" },
	{ ["text"] = "cry", ["subText"] = "(╥﹏╥)" },
	{ ["text"] = "crywave", ["subText"] = "( ╥﹏╥) ノシ" },
	{ ["text"] = "cute", ["subText"] = "(｡◕‿‿◕｡)" },
	{ ["text"] = "d1", ["subText"] = "⚀" },
	{ ["text"] = "d2", ["subText"] = "⚁" },
	{ ["text"] = "d3", ["subText"] = "⚂" },
	{ ["text"] = "d4", ["subText"] = "⚃" },
	{ ["text"] = "d5", ["subText"] = "⚄" },
	{ ["text"] = "d6", ["subText"] = "⚅" },
	{ ["text"] = "dab", ["subText"] = "ヽ( •_)ᕗ" },
	{ ["text"] = "damnyou", ["subText"] = "(ᕗ ͠° ਊ ͠° )ᕗ" },
	{ ["text"] = "dance", ["subText"] = "ᕕ(⌐■_■)ᕗ ♪♬" },
	{ ["text"] = "dead", ["subText"] = "x⸑x" },
	{ ["text"] = "dealwithit,dwi", ["subText"] = "(⌐■_■)" },
	{ ["text"] = "delta", ["subText"] = "Δ" },
	{ ["text"] = "depressed", ["subText"] = "(︶︹︶)" },
	{ ["text"] = "derp", ["subText"] = "☉ ‿ ⚆" },
	{ ["text"] = "diamond", ["subText"] = "♦" },
	{ ["text"] = "dj", ["subText"] = "d[-_-]b" },
	{ ["text"] = "dog", ["subText"] = "(◕ᴥ◕ʋ)" },
	{ ["text"] = "dollar", ["subText"] = "$" },
	{ ["text"] = "dong", ["subText"] = "(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄" },
	{ ["text"] = "donger", ["subText"] = "ヽ༼ຈل͜ຈ༽ﾉ" },
	{ ["text"] = "dontcare,idc", ["subText"] = "(- ʖ̯-)" },
	{ ["text"] = "donotwant,do", ["subText"] = "not want,dontwant ヽ(｀Д´)ﾉ" },
	{ ["text"] = "dope", ["subText"] = "<(^_^)>" },
	{ ["text"] = "doublequotesleft,<<", ["subText"] = "«" },
	{ ["text"] = "doublequotesright,>>", ["subText"] = "»" },
	{ ["text"] = "doubleflat", ["subText"] = "𝄫" },
	{ ["text"] = "doublesharp", ["subText"] = "𝄪" },
	{ ["text"] = "doubletableflip", ["subText"] = "┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻" },
	{ ["text"] = "down", ["subText"] = "↓" },
	{ ["text"] = "duckface", ["subText"] = "(・3・)" },
	{ ["text"] = "duel", ["subText"] = "ᕕ(╭ರ╭ ͟ʖ╮•́)⊃¤=(————-" },
	{ ["text"] = "duh", ["subText"] = "(≧︿≦)" },
	{ ["text"] = "dunnolol,dunno", ["subText"] = "¯\\(°_o)/¯" },
	{ ["text"] = "ebola", ["subText"] = "ᴇʙᴏʟᴀ" },
	{ ["text"] = "eeriemob", ["subText"] = "(-(-_-(-_(-_(-_-)_-)-_-)_-)_-)-)" },
	{ ["text"] = "ellipsis,...", ["subText"] = "…" },
	{ ["text"] = "emdash,--", ["subText"] = "–" },
	{ ["text"] = "emptystar", ["subText"] = "☆" },
	{ ["text"] = "emptytriangle,t2", ["subText"] = "△" },
	{ ["text"] = "endure", ["subText"] = "(҂◡_◡) ᕤ" },
	{ ["text"] = "envelope,letter", ["subText"] = "✉︎" },
	{ ["text"] = "epsilon", ["subText"] = "ɛ" },
	{ ["text"] = "euro", ["subText"] = "€" },
	{ ["text"] = "evil", ["subText"] = "ψ(｀∇´)ψ" },
	{ ["text"] = "evillenny", ["subText"] = "(͠≖ ͜ʖ͠≖)" },
	{ ["text"] = "excited", ["subText"] = "(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧" },
	{ ["text"] = "execution", ["subText"] = "(⌐■_■)︻╦╤─   (╥﹏╥)" },
	{ ["text"] = "facebook", ["subText"] = "(╯°□°)╯︵ ʞooqǝɔɐɟ" },
	{ ["text"] = "facepalm", ["subText"] = "(－‸ლ)" },
	{ ["text"] = "fart", ["subText"] = "(ˆ⺫ˆ๑)<3" },
	{ ["text"] = "fight", ["subText"] = "(ง •̀_•́)ง" },
	{ ["text"] = "finn", ["subText"] = "| (• ◡•)|" },
	{ ["text"] = "fish", ["subText"] = '<"(((<3' },
	{ ["text"] = "five,5", ["subText"] = "卌" },
	{ ["text"] = "fiveeights,5/8", ["subText"] = "⅝" },
	{ ["text"] = "flat,bemolle", ["subText"] = "♭" },
	{ ["text"] = "flexing", ["subText"] = "ᕙ(`▽´)ᕗ" },
	{ ["text"] = "flipped,heavytable", ["subText"] = "┬─┬﻿ ︵ /(.□. \\）" },
	{ ["text"] = "flower,flor", ["subText"] = "(✿◠‿◠)" },
	{ ["text"] = "flower2,f", ["subText"] = "✿" },
	{ ["text"] = "fly", ["subText"] = "─=≡Σ((( つ◕ل͜◕)つ" },
	{ ["text"] = "friendflip", ["subText"] = "(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)" },
	{ ["text"] = "frown", ["subText"] = "(ღ˘⌣˘ღ)" },
	{ ["text"] = "fuckoff,gtfo", ["subText"] = "୧༼ಠ益ಠ╭∩╮༽" },
	{ ["text"] = "fuckyou,fu", ["subText"] = "┌П┐(ಠ_ಠ)" },
	{ ["text"] = "gentleman,sir,monocle", ["subText"] = "ಠ_ರೃ" },
	{ ["text"] = "ghast", ["subText"] = "= _ =" },
	{ ["text"] = "ghost", ["subText"] = "༼ つ ╹ ╹ ༽つ" },
	{ ["text"] = "gift,present", ["subText"] = "(´・ω・)っ由" },
	{ ["text"] = "gimme", ["subText"] = "༼ つ ◕_◕ ༽つ" },
	{ ["text"] = "givemeyourmoney", ["subText"] = "(•-•)⌐" },
	{ ["text"] = "glitterbomb,glitter", ["subText"] = "(*・‿・)ノ⌒*:･ﾟ✧" },
	{ ["text"] = "glasses", ["subText"] = "(⌐ ͡■ ͜ʖ ͡■)" },
	{ ["text"] = "glassesoff", ["subText"] = "( ͡° ͜ʖ ͡°)ﾉ⌐■-■" },
	{ ["text"] = "glitterderp", ["subText"] = "(ﾉ☉ヮ⚆)ﾉ ⌒*:･ﾟ✧" },
	{ ["text"] = "gloomy", ["subText"] = "(_゜_゜_)" },
	{ ["text"] = "goatse", ["subText"] = "(з๏ε)" },
	{ ["text"] = "gotit", ["subText"] = "(☞ﾟ∀ﾟ)☞" },
	{ ["text"] = "greet,greetings", ["subText"] = "( ´◔ ω◔`) ノシ" },
	{ ["text"] = "gun,mg", ["subText"] = "︻╦╤─" },
	{ ["text"] = "hadouken", ["subText"] = "༼つಠ益ಠ༽つ ─=≡ΣO))" },
	{ ["text"] = "hammerandsickle,hs", ["subText"] = "☭" },
	{ ["text"] = "handleft,hl", ["subText"] = "☜" },
	{ ["text"] = "handright,hr", ["subText"] = "☞" },
	{ ["text"] = "haha", ["subText"] = "٩(^‿^)۶" },
	{ ["text"] = "happy", ["subText"] = "٩( ๑╹ ꇴ╹)۶" },
	{ ["text"] = "happygarry", ["subText"] = "ᕕ( ᐛ )ᕗ" },
	{ ["text"] = "heart,h", ["subText"] = "♥" },
	{ ["text"] = "hello,ohai,bye", ["subText"] = "(ʘ‿ʘ)╯" },
	{ ["text"] = "help", ["subText"] = "\\(°Ω°)/" },
	{ ["text"] = "highfive", ["subText"] = "._.)/\\(._." },
	{ ["text"] = "hitting", ["subText"] = "( ｀皿´)｡ﾐ/" },
	{ ["text"] = "hugs,hug", ["subText"] = "(づ｡◕‿‿◕｡)づ" },
	{ ["text"] = "iknowright,ikr", ["subText"] = "┐｜･ิω･ิ#｜┌" },
	{ ["text"] = "illuminati", ["subText"] = "୧(▲ᴗ▲)ノ" },
	{ ["text"] = "infinity,inf", ["subText"] = "∞" },
	{ ["text"] = "inlove", ["subText"] = "(っ´ω`c)♡" },
	{ ["text"] = "integral,int", ["subText"] = "∫" },
	{ ["text"] = "internet", ["subText"] = "ଘ(੭*ˊᵕˋ)੭* ̀ˋ ɪɴᴛᴇʀɴᴇᴛ" },
	{ ["text"] = "interrobang", ["subText"] = "‽" },
	{ ["text"] = "jake", ["subText"] = "(❍ᴥ❍ʋ)" },
	{ ["text"] = "kappa", ["subText"] = "(¬,‿,¬)" },
	{ ["text"] = "kawaii", ["subText"] = "≧◡≦" },
	{ ["text"] = "keen", ["subText"] = "┬┴┬┴┤Ɵ͆ل͜Ɵ͆ ༽ﾉ" },
	{ ["text"] = "kiahh", ["subText"] = "~\\(≧▽≦)/~" },
	{ ["text"] = "kiss", ["subText"] = "(づ ￣ ³￣)づ" },
	{ ["text"] = "kyubey", ["subText"] = "／人◕ ‿‿ ◕人＼" },
	{ ["text"] = "lambda", ["subText"] = "λ" },
	{ ["text"] = "lazy", ["subText"] = "_(:3」∠)_" },
	{ ["text"] = "left,<-", ["subText"] = "←" },
	{ ["text"] = "lenny", ["subText"] = "( ͡° ͜ʖ ͡°)" },
	{ ["text"] = "lennybill", ["subText"] = "[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]" },
	{ ["text"] = "lennyfight", ["subText"] = "(ง ͠° ͟ʖ ͡°)ง" },
	{ ["text"] = "lennyflip", ["subText"] = "(ノ ͡° ͜ʖ ͡°ノ)   ︵ ( ͜。 ͡ʖ ͜。)" },
	{ ["text"] = "lennygang", ["subText"] = "( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)" },
	{ ["text"] = "lennyshrug", ["subText"] = "¯\\_( ͡° ͜ʖ ͡°)_/¯" },
	{ ["text"] = "lennysir", ["subText"] = "( ಠ ͜ʖ ರೃ)" },
	{ ["text"] = "lennystalker", ["subText"] = "┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴" },
	{ ["text"] = "lennystrong", ["subText"] = "ᕦ( ͡° ͜ʖ ͡°)ᕤ" },
	{ ["text"] = "lennywizard", ["subText"] = "╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ" },
	{ ["text"] = "lol", ["subText"] = "L(° O °L)" },
	{ ["text"] = "look", ["subText"] = "(ಡ_ಡ)☞" },
	{ ["text"] = "loud,noise", ["subText"] = "ᕦ(⩾﹏⩽)ᕥ" },
	{ ["text"] = "love", ["subText"] = "♥‿♥" },
	{ ["text"] = "lovebear", ["subText"] = "ʕ♥ᴥ♥ʔ" },
	{ ["text"] = "lumpy", ["subText"] = "꒰ ꒡⌓꒡꒱" },
	{ ["text"] = "luv", ["subText"] = "-`ღ´-" },
	{ ["text"] = "magic", ["subText"] = "ヽ(｀Д´)⊃━☆ﾟ. * ･ ｡ﾟ," },
	{ ["text"] = "magicflip", ["subText"] = "(/¯◡ ‿ ◡)/¯ ~ ┻━┻" },
	{ ["text"] = "meep", ["subText"] = "\\(°^°)/" },
	{ ["text"] = "meh", ["subText"] = "ಠ_ಠ" },
	{ ["text"] = "metal,rock", ["subText"] = "\\m/,(> . <)_\\m/" },
	{ ["text"] = "mistyeyes", ["subText"] = "ಡ_ಡ" },
	{ ["text"] = "monster", ["subText"] = "༼ ༎ຶ ෴ ༎ຶ༽" },
	{ ["text"] = "natural", ["subText"] = "♮" },
	{ ["text"] = "needle,inject", ["subText"] = "┌(◉ ͜ʖ◉)つ┣▇▇▇═──" },
	{ ["text"] = "nerd", ["subText"] = "(⌐⊙_⊙)" },
	{ ["text"] = "nice", ["subText"] = "( ͡° ͜ °)" },
	{ ["text"] = "no", ["subText"] = "→_←" },
	{ ["text"] = "noclue", ["subText"] = "／人◕ __ ◕人＼" },
	{ ["text"] = "nom,yummy,delicious", ["subText"] = "(っˆڡˆς)" },
	{ ["text"] = "note,sing", ["subText"] = "♫" },
	{ ["text"] = "nuclear,radioactive,nukular", ["subText"] = "☢" },
	{ ["text"] = "nyan", ["subText"] = "~=[,,_,,]:3" },
	{ ["text"] = "nyeh", ["subText"] = "@^@" },
	{ ["text"] = "ohshit", ["subText"] = "( º﹃º )" },
	{ ["text"] = "omega", ["subText"] = "Ω" },
	{ ["text"] = "omg", ["subText"] = "◕_◕" },
	{ ["text"] = "oneeighth,1/8", ["subText"] = "⅛" },
	{ ["text"] = "onefourth,1/4", ["subText"] = "¼" },
	{ ["text"] = "onehalf,1/2", ["subText"] = "½" },
	{ ["text"] = "onethird,1/3", ["subText"] = "⅓" },
	{ ["text"] = "option,opt", ["subText"] = "⌥" },
	{ ["text"] = "ohreally,orly", ["subText"] = "(눈_눈)" },
	{ ["text"] = "ohyou,ou", ["subText"] = "(◞థ౪థ)ᴖ" },
	{ ["text"] = "peace,victory", ["subText"] = "✌(-‿-)✌" },
	{ ["text"] = "pear", ["subText"] = "(__>-" },
	{ ["text"] = "pi", ["subText"] = "π" },
	{ ["text"] = "pingpong", ["subText"] = "( •_•)O*¯`·.¸.·´¯`°Q(•_• )" },
	{ ["text"] = "plain", ["subText"] = "._." },
	{ ["text"] = "pleased", ["subText"] = "(˶‾᷄ ⁻̫ ‾᷅˵)" },
	{ ["text"] = "point", ["subText"] = "(☞ﾟヮﾟ)☞" },
	{ ["text"] = "pooh", ["subText"] = "ʕ •́؈•̀)" },
	{ ["text"] = "porcupine", ["subText"] = "(•ᴥ• )́`́'́`́'́⻍" },
	{ ["text"] = "pound", ["subText"] = "£" },
	{ ["text"] = "praise", ["subText"] = "(☝ ՞ਊ ՞)☝" },
	{ ["text"] = "punch", ["subText"] = "O=('-'Q)" },
	{ ["text"] = "rage,mad", ["subText"] = "t(ಠ益ಠt)" },
	{ ["text"] = "rageflip", ["subText"] = "(ノಠ益ಠ)ノ彡┻━┻" },
	{ ["text"] = "rainbowcat", ["subText"] = "(=^･ｪ･^=))ﾉ彡☆" },
	{ ["text"] = "really", ["subText"] = "ò_ô" },
	{ ["text"] = "registered,r", ["subText"] = "®" },
	{ ["text"] = "right,->", ["subText"] = "→" },
	{ ["text"] = "riot", ["subText"] = "୧༼ಠ益ಠ༽୨" },
	{ ["text"] = "rolleyes", ["subText"] = "(◔_◔)" },
	{ ["text"] = "rose", ["subText"] = "✿ڿڰۣ—" },
	{ ["text"] = "run", ["subText"] = "(╯°□°)╯" },
	{ ["text"] = "sad", ["subText"] = "ε(´סּ︵סּ`)з" },
	{ ["text"] = "saddonger", ["subText"] = "ヽ༼ຈʖ̯ຈ༽ﾉ" },
	{ ["text"] = "sadlenny", ["subText"] = "( ͡° ʖ̯ ͡°)" },
	{ ["text"] = "seveneigths,7/8", ["subText"] = "⅞" },
	{ ["text"] = "sharp,diesis", ["subText"] = "♯" },
	{ ["text"] = "shout", ["subText"] = "╚(•⌂•)╝" },
	{ ["text"] = "shrug", ["subText"] = "¯\\_(ツ)_/¯" },
	{ ["text"] = "shy", ["subText"] = "=^_^=" },
	{ ["text"] = "sigma,sum", ["subText"] = "Σ" },
	{ ["text"] = "skull", ["subText"] = "☠" },
	{ ["text"] = "smile", ["subText"] = "ツ" },
	{ ["text"] = "smiley", ["subText"] = "☺︎" },
	{ ["text"] = "smirk", ["subText"] = "¬‿¬" },
	{ ["text"] = "snowman", ["subText"] = "☃" },
	{ ["text"] = "sob", ["subText"] = "(;´༎ຶД༎ຶ`)" },
	{ ["text"] = "soviettableflip", ["subText"] = "ノ┬─┬ノ ︵ ( \\o°o)\\" },
	{ ["text"] = "spade", ["subText"] = "♠" },
	{ ["text"] = "squareroot,sqrt", ["subText"] = "√" },
	{ ["text"] = "squid", ["subText"] = "<コ:彡" },
	{ ["text"] = "star", ["subText"] = "★" },
	{ ["text"] = "strong", ["subText"] = "ᕙ(⇀‸↼‶)ᕗ" },
	{ ["text"] = "suicide", ["subText"] = "ε/̵͇̿̿/’̿’̿ ̿(◡︵◡)" },
	{ ["text"] = "sum", ["subText"] = "∑" },
	{ ["text"] = "sun", ["subText"] = "☀" },
	{ ["text"] = "surprised", ["subText"] = "(๑•́ ヮ •̀๑)" },
	{ ["text"] = "surrender", ["subText"] = "_(-_-)_/" },
	{ ["text"] = "stalker", ["subText"] = "┬┴┬┴┤(･_├┬┴┬┴" },
	{ ["text"] = "swag", ["subText"] = "(̿▀̿‿ ̿▀̿ ̿)" },
	{ ["text"] = "sword", ["subText"] = "o()xxxx[{::::::::::::::::::>" },
	{ ["text"] = "tabledown", ["subText"] = "┬─┬﻿ ノ( ゜-゜ノ)" },
	{ ["text"] = "tableflip", ["subText"] = "(ノ ゜Д゜)ノ ︵ ┻━┻" },
	{ ["text"] = "tau", ["subText"] = "τ" },
	{ ["text"] = "tears", ["subText"] = "(ಥ﹏ಥ)" },
	{ ["text"] = "terrorist", ["subText"] = "୧༼ಠ益ಠ༽︻╦╤─" },
	{ ["text"] = "thanks,thankyou,ty", ["subText"] = "(^-^)/" },
	{ ["text"] = "therefore,so", ["subText"] = "⸫" },
	{ ["text"] = "thisis,this", ["subText"] = "( ͡° ͜ʖ ͡°)_/¯" },
	{ ["text"] = "threeeights,3/8", ["subText"] = "⅜" },
	{ ["text"] = "tiefighter", ["subText"] = "|=-(¤)-=|" },
	{ ["text"] = "tired", ["subText"] = "(=____=)" },
	{ ["text"] = "toldyouso,toldyou", ["subText"] = "☜(꒡⌓꒡)" },
	{ ["text"] = "toogood", ["subText"] = "ᕦ(òᴥó)ᕥ" },
	{ ["text"] = "trademark,tm", ["subText"] = "™" },
	{ ["text"] = "triangle,t", ["subText"] = "▲" },
	{ ["text"] = "twothirds,2/3", ["subText"] = "⅔" },
	{ ["text"] = "unflip", ["subText"] = "┬──┬ ノ(ò_óノ)" },
	{ ["text"] = "up", ["subText"] = "↑" },
	{ ["text"] = "victory", ["subText"] = "(๑•̀ㅂ•́)ง✧" },
	{ ["text"] = "wat", ["subText"] = "(ÒДÓױ)" },
	{ ["text"] = "wave", ["subText"] = "( * ^ *) ノシ" },
	{ ["text"] = "whaa", ["subText"] = "Ö" },
	{ ["text"] = "whistle", ["subText"] = "(っ^з^)♪♬" },
	{ ["text"] = "whoa", ["subText"] = "(°o•)" },
	{ ["text"] = "why", ["subText"] = "ლ(`◉◞౪◟◉‵ლ)" },
	{ ["text"] = "woo", ["subText"] = "＼(＾O＾)／" },
	{ ["text"] = "wtf", ["subText"] = "(⊙＿⊙')" },
	{ ["text"] = "wut", ["subText"] = "⊙ω⊙" },
	{ ["text"] = "yay", ["subText"] = "\\( ﾟヮﾟ)/" },
	{ ["text"] = "yeah,yes", ["subText"] = "(•̀ᴗ•́)و ̑̑" },
	{ ["text"] = "yen", ["subText"] = "¥" },
	{ ["text"] = "yinyang,yy", ["subText"] = "☯" },
	{ ["text"] = "yolo", ["subText"] = "Yᵒᵘ Oᶰˡʸ Lᶤᵛᵉ Oᶰᶜᵉ" },
	{ ["text"] = "youkids,ukids", ["subText"] = "ლ༼>╭ ͟ʖ╮<༽ლ" },
	{ ["text"] = "yuno,y", ["subText"] = "u no (屮ﾟДﾟ)屮 Y U NO" },
	{ ["text"] = "zen,meditation,omm", ["subText"] = "⊹╰(⌣ʟ⌣)╯⊹" },
	{ ["text"] = "zoidberg", ["subText"] = "(V) (°,,,,°) (V)" },
	{ ["text"] = "zombie", ["subText"] = "[¬º-°]¬" },
}
return asciimojis
